import { Roboto } from "next/font/google"; 
import "./globals.css";
import Left from './leftnav/page'

const roboto = Roboto({
  variable: "--font-roboto", 
  subsets: ["latin"],  
  weight:["100","300","400","500","700","900"]
});

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}> 
        <Left />
        {children}
      </body>
    </html>
  );
}
